-- ============================================================
-- PIRO · BDDI — Modelagem das tabelas (Oracle Database FIAP)
-- Host: oracle.fiap.com.br  Porta: 1521  SID: ORCL
-- ============================================================
-- 3 tabelas relacionadas:
--   focos_incendio (1) --- (N) clima_associado
--   focos_incendio (1) --- (N) imagens_satelite_metadata
-- Rode no SQL Developer ou DBeaver conectado ao banco da FIAP.
-- ============================================================

-- Limpeza (ignore erros na 1a execucao)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE imagens_satelite_metadata'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE clima_associado'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE focos_incendio'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ------------------------------------------------------------
-- Tabela 1: focos_incendio
-- ------------------------------------------------------------
CREATE TABLE focos_incendio (
    id_foco       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_externo    VARCHAR2(60)  NOT NULL UNIQUE,   -- id do satelite/FIRMS (lat|lon|data|hora)
    latitude      NUMBER(9,4)   NOT NULL,
    longitude     NUMBER(9,4)   NOT NULL,
    data_foco     DATE          NOT NULL,
    satelite      VARCHAR2(20),
    confianca     NUMBER(5,1),                     -- % de confianca
    brilho        NUMBER(7,1),                     -- temperatura de brilho (K)
    frp           NUMBER(8,1),                     -- Fire Radiative Power (MW)
    estado        VARCHAR2(2),
    bioma         VARCHAR2(20)
);

-- ------------------------------------------------------------
-- Tabela 2: clima_associado  (FK -> focos_incendio)
-- ------------------------------------------------------------
CREATE TABLE clima_associado (
    id_clima      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_externo    VARCHAR2(60)  NOT NULL UNIQUE,    -- 1:1 com focos_incendio
    temperatura   NUMBER(5,1),
    umidade       NUMBER(5,1),
    vento         NUMBER(5,1),
    precipitacao  NUMBER(6,1),
    estacao_seca  NUMBER(1),                        -- 0/1
    CONSTRAINT fk_clima_foco FOREIGN KEY (id_externo)
        REFERENCES focos_incendio (id_externo)
);

-- ------------------------------------------------------------
-- Tabela 3: imagens_satelite_metadata  (FK -> focos_incendio)
-- Liga a classificacao da CNN (disciplina ACV) ao foco.
-- ------------------------------------------------------------
CREATE TABLE imagens_satelite_metadata (
    id_imagem        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_externo       VARCHAR2(60) NOT NULL,
    url_tile         VARCHAR2(400),
    resolucao        VARCHAR2(20),
    classificacao    VARCHAR2(20),                  -- 'fogo' / 'nao_fogo'
    confianca_cnn    NUMBER(5,1),
    CONSTRAINT fk_img_foco FOREIGN KEY (id_externo)
        REFERENCES focos_incendio (id_externo)
);

-- ------------------------------------------------------------
-- Indices em colunas de busca frequente (desempenho das consultas)
-- ------------------------------------------------------------
CREATE INDEX idx_focos_data   ON focos_incendio (data_foco);
CREATE INDEX idx_focos_estado ON focos_incendio (estado);
CREATE INDEX idx_focos_bioma  ON focos_incendio (bioma);
CREATE INDEX idx_clima_idext  ON clima_associado (id_externo);

COMMIT;
-- Conferencia rapida:
-- SELECT table_name FROM user_tables WHERE table_name LIKE '%FOCOS%' OR table_name LIKE '%CLIMA%' OR table_name LIKE '%IMAGENS%';
